defaults:
  - override hydra/job_logging: disabled
  
data_path: "data"
results_dir: "results"

model: "DiT-XL"   # choices: [list(DiT_models.keys())]

epochs: 100
batch_size: 64
seed: 42
num_workers: 4

log_every: 50
ckpt_every: 5000

wandb:
  project: "oracle"
  name: "yfinance-XL-cfg-decoded"
  log: True