# config/config.yaml

defaults:
  - override hydra/job_logging: disabled  # Optional: disable hydra logs

seed: 42
data:
  val_ratio: 0.2
  batch_size: 256
  num_workers: 4

model:
  nodes: [181, 1024, 512, 256, 128, 64, 128, 256, 512, 1024, 362]
  timesteps: 1000

train:
  epochs: 30
  lr: 0.001
  use_compile: False
  save: True
  epoch_save: False

wandb:
  project: "oracle"
  name: "vanilla-fourier"
  log: False